#JSON Path
ftpjson:
  devices-path: E:\lwj-data\FTPJson\201905140840\devices
  servers-path: E:\lwj-data\FTPJson\201905140840\servers
  manage-path: E:\lwj-data\FTPJson\201905140840\manage
  resource-path: E:\lwj-data\FTPJson\201905140840\resource
  system-path: E:\lwj-data\FTPJson\201905140840\system

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    #=============== provider  =======================
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    #=============== consumer  =======================
    consumer:
      group-id: testGroup
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

redis:
  host: 127.0.0.1
  port: 6379
  database: 0
  pool:
    max-active: 100
    max-idle: 10
  cache:
    expiration: 3601





